[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]
runner = "blflash flash --port /dev/ttyUSB0"

[build]
target = "riscv32imac-unknown-none-elf"
